name: publish to nuget
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
        
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Numani.TypedFilePath/Numani.TypedFilePath.csproj
          NUGET_KEY: oy2dya5j5wnv757gjzsae55pycsorcsuxhgmsjnr6ovzgm # optional
          INCLUDE_SYMBOLS: false # optional
